version: '3.9'

services:

  postgres-db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: docker123
      POSTGRES_DB: proposal
    ports:
      - '5434:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin@password
    ports:
      - '15434:80'
    depends_on:
      - postgres-db

#docker run -d -p 5672:5672 -p 15672:15672 --name my-rabbit rabbitmq:3-management
#user: guest  password: guest